#Photo Booth Config:
"TOTAL_PICS"        : 4  # Number of pics to be taken
"PREP_DELAY"        : 4  # Number of seconds as users prepare to have photo taken, before countdown commences
"COUNTDOWN"         : 2  # Number of seconds to count down from

# Take photos at this resolution:
"PHOTO_W"           : 2048
"PHOTO_H"           : 1536

# Resolution of the photo booth display:
"SCREEN_W"          : 1024
"SCREEN_H"          : 768

# Camera setup
"CAMERA_ROTATION"   : 180 # Rotation of the camera
"CAMERA_HFLIP"      : True # When preparing for photos, the preview will be flipped horizontally.

# Primary folder to save images to (required):
"SAVE_RAW_IMAGES_FOLDER" : "photos"
